services:
  subpub:
    build:
      context: service
    image: apiserver:latest
    container_name: apiserver
    restart: unless-stopped
    ports:
      - 50051:50051
    volumes:
      - type: bind
        source: ./config.yaml
        target: /config.yaml
        read_only: true

  tests:
    build:
      context: tests
    image: apitest:latest
    container_name: apitest
    restart: "no"
