---
app:
  environment: dev # dev, prod
  name: subpub-service
  version: 0.1.0

grpc_server:
  port: 50051
  max_idle: 10s
  timeout: 5s
  startup_delay: 1s
  shutdown_period: 7s
  publish_retry_attempts: 3
  publish_retry_backoff: 100ms
